title: Page
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
      tabs:
          type: tabs
          active: 1

      fields:
          type: tab
          title: Fields

          fields:
              header.image_icon:
                  type: toggle
                  label: Image Icon
                  highlight: 1
                  default: false
                  options:
                      '1': PLUGIN_ADMIN.YES
                      '0': PLUGIN_ADMIN.NO
                  validate:
                      type: bool
              header.swiper:
                  type: toggle
                  label: Swiper
                  highlight: 1
                  default: true
                  options:
                      '1': PLUGIN_ADMIN.YES
                      '0': PLUGIN_ADMIN.NO
                  validate:
                      type: bool
