title: default
'@extends':
    type: default
    context: blueprints://pages

form:
  fields:
    tabs:
      fields:
        content:
          type: tab
          title: Inhalt
          fields:
            header.bootstrap:
              type: toggle
              label: Bootstrap
              highlight: false
              default: false
              options:
                true: 'Ja'
                false: 'Nein'
              validate:
                type: bool
            header.swiper:
              type: toggle
              label: Bild-Swiper
              highlight: false
              default: false
              options:
                true: 'Ja'
                false: 'Nein'
              validate:
                type: bool